Feature/atualizar salario
Pajp-Proprietario/ProjetoSQL pull request #2
Opened 2024-03-18 19:21 UTC by wulkmor

Nesta branch fiz tudo que foi solicitado na tarefa1:

1 - Crie uma função que receba o ID de um cliente e retorne o total de pedidos feitos por esse cliente.
2 - Escreva um procedimento que atualize o preço de todos os produtos em uma determinada categoria para um novo valor fornecido como entrada.
3 - Desenvolva um bloco anônimo que calcule o total de vendas em um determinado mês e ano.
4 - Crie uma função que receba o ID de um produto e retorne o total de unidades vendidas desse produto em um intervalo de datas específico.
5 - Escreva um procedimento que insira um novo funcionário na tabela de funcionários, garantindo que o novo funcionário tenha um número de identificação único e válido.

2024-03-18 19:26 UTC, Pajp-Proprietario commented
Na questão "3 - Desenvolva um bloco anônimo que calcule o total de vendas em um determinado mês e ano." vc não quis fazer em bloco anônimo? @wulkmor

2024-03-19 17:03 UTC, wulkmor commented
> Na questão "3 - Desenvolva um bloco anônimo que calcule o total de vendas em um determinado mês e ano." vc não quis fazer em bloco anônimo? @wulkmor

Eu achei melhor fazer dentro de uma function!

2024-03-19 17:06 UTC, Pajp-Proprietario reviewed
teste

2024-03-19 17:06 UTC, Pajp-Proprietario commented on Scripts/pk_gestao_vendas.sql
> +    /*3 - Desenvolva um bloco an�nimo que calcule o total de vendas em um determinado m�s e ano. (vou fazer em uma funcion mesmo)*/
Aqui?

2024-03-19 17:10 UTC, wulkmor commented on Scripts/pk_gestao_vendas.sql
> +    end fn_qtd_unidades_vendidas;
Gostei desta function!

2024-03-19 17:18 UTC, Pajp-Proprietario requested changes
teste 4

2024-03-19 17:18 UTC, Pajp-Proprietario commented on Scripts/pk_gestao_vendas.sql
> +        where ped.id_cli = p_cd_cliente;
muda o alias da tabela pra testar um negócio aqui

2024-03-19 17:20 UTC, wulkmor commented on Scripts/pk_gestao_vendas.sql
> +        where ped.id_cli = p_cd_cliente;
Não vai impactar em nada

2024-03-19 17:25 UTC, Pajp-Proprietario approved these changes
Aprovado!

2024-03-19 17:26 UTC, merged